import type { ItemType } from './components/Item'

export const exampleCardItems: { type: ItemType; label: string }[] = [
    { type: 'person', label: 'Persona, Ser o Lugar' },
    { type: 'object', label: 'Objeto' },
    { type: 'action', label: 'Accion' },
    { type: 'difficult', label: 'Dificil' },
    { type: 'allplay', label: 'Todos Juegan' }
]

const countries = ["Afganistán",
    "Albania",
    "Alemania",
    "Andorra",
    "Arabia Saudita",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Bahamas",
    "Bangladés",
    "Barbados",
    "Bélgica",
    "Bolivia",
    "Brasil",
    "Burkina Faso",
    "Camerún",
    "Canadá",
    "Catar",
    "Chad",
    "Chile",
    "China",
    "Ciudad del Vaticano",
    "Colombia",
    "Corea del Norte",
    "Corea del Sur",
    "Costa Rica",
    "Croacia",
    "Cuba",
    "Dinamarca",
    "Dominica",
    "Ecuador",
    "Egipto",
    "El Salvador",
    "Emiratos Árabes Unidos",
    "España",
    "Estados Unidos",
    "Estonia",
    "Etiopía",
    "Filipinas",
    "Finlandia",
    "Fiyi",
    "Francia",
    "Grecia",
    "Guatemala",
    "Haití",
    "Honduras",
    "Hungría",
    "India",
    "Indonesia",
    "Irak",
    "Irán",
    "Irlanda",
    "Islandia",
    "Israel",
    "Italia",
    "Jamaica",
    "Japón",
    "Jordania",
    "Kenia",
    "Kuwait",
    "Laos",
    "Lesoto",
    "Letonia",
    "Líbano",
    "Liberia",
    "Libia",
    "Lituania",
    "Luxemburgo",
    "Madagascar",
    "Malasia",
    "Malaui",
    "Maldivas",
    "Malí",
    "Malta",
    "Marruecos",
    "México",
    "Moldavia",
    "Mónaco",
    "Mongolia",
    "Montenegro",
    "Mozambique",
    "Namibia",
    "Nepal",
    "Nicaragua",
    "Níger",
    "Nigeria",
    "Noruega",
    "Nueva Zelanda",
    "Omán",
    "Países Bajos",
    "Pakistán",
    "Panamá",
    "Papúa Nueva Guinea",
    "Paraguay",
    "Perú",
    "Polonia",
    "Portugal",
    "Reino Unido",
    "República Checa",
    "República Dominicana",
    "Rumanía",
    "Rusia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Singapur",
    "Siria",
    "Somalia",
    "Suecia",
    "Suiza",
    "Tailandia",
    "Turquía",
    "Ucrania",
    "Uganda",
    "Uruguay",
    "Venezuela",
    "Vietnam",
]
const profesiones = [
    'Abogado', 'Actor', 'Actriz', 'Administrador', 'Agricultor', 'Albañil',
    'Intendente', 'Ama de casa', 'Anestesista',
    'Arqueólogo', 'Arquitecto', 'Artista', 'Astrónomo', 'Atleta', 'Arbitro',
    'Bailarín', 'Banquero', 'Peluquero', 'Biólogo',
    'Bombero', 'Botánico', 'Cajero', 'Carpintero', 'Cartero', 'Cocinero',
    'Contador', 'Dentista', 'Diseñador', 'Director de cine',
    'Economista', 'Electricista', 'Enfermero', 'Escritor', 'Estilista',
    'Fotógrafo', 'Físico', 'Geólogo', 'Gerente',
    'Guía turístico', 'Ingeniero', 'Intérprete', 'Jardinero',
    'Jefe de cocina', 'Juez', 'Librero', 'Locutor', 'Mecánico',
    'Médico', 'Mesero', 'Modelo', 'Musico',
    'Obrero', 'Optometrista', 'Pediatra',
    'Periodista', 'Piloto', 'Plomero', 'Político', 'Profesor', 'Policia',
    'Psicólogo', 'Químico', 'Recepcionista',
    'Reportero', 'Secretario', 'Soldador', 'Taxista',
    'Técnico', 'Traductor', 'Veterinario', 'Panadero', 'Rabino', 'Sacerdote', 'Monje', 'Monja'
]
const animales = [
    'León', 'Tigre', 'Elefante', 'Jirafa', 'Mono', 'Perro', 'Gato', 'Caballo',
    'Vaca', 'Cerdo', 'Oveja', 'Cabra', 'Lechuza', 'Búho', 'Águila', 'Halcón',
    'Delfín', 'Ballena', 'Tiburón', 'Pulpo', 'Araña', 'Mariposa', 'Grillo',
    'Hormiga', 'Saltamontes', 'Canguro', 'Koala', 'Panda', 'Zorro', 'Ornitorrinco',
    'Lobo', 'Cebra', 'Rinoceronte', 'Hipopótamo', 'Cangrejo', 'Langosta',
    'Caracol', 'Mariposa Monarca', 'Escorpión', 'Serpiente', 'Tortuga',
    'Pingüino', 'Foca', 'Nutria', 'Castor', 'Armadillo', 'Camaron',
    'Medusa', 'Estrella de mar', 'Erizo de mar', 'Pulga',
    'Mosquito', 'Avispa', 'Abeja', 'Libélula',
    'Escarabajo', 'Cucaracha',
]
const lugaresGenericos = [
    'Bosque', 'Montaña', 'Valle', 'Desierto', 'Isla', 'Playa', 'Lago',
    'Río', 'Océano', 'Castillo', 'Iglesia', 'Museo', 'Teatro', 'Estadio',
    'Parque', 'Jardín', 'Zoologico', 'Biblioteca', 'Universidad',
    'Hospital', 'Restaurante', 'Cafetería', 'Bar', 'Supermercado',
    'Mercado', 'Plaza', 'Estación de tren', 'Aeropuerto', 'Puerto',
    'Fábrica', 'Oficina', 'Banco', 'Hotel',
    'Catedral', 'Monumento', 'Palacio', 'Cueva', 'Granja', 'Estación espacial',
    'Acantilado', 'Cañón', 'Pantano', 'Glaciar', 'Volcán', 'Rancheria',
    'Cabaña', 'Refugio', 'Cementerio', 'Parque Nacional', 'Reserva Natural',
    'Zona Arqueológica', 'Mirador', 'Ciudad Abandonada',
    'Faro', 'Mercado Nocturno', 'Centro Comercial', 'Terminal de buses'
]
const personasGenericas = [
    'Amigo', 'Hermano', 'Jefe', 'Estudiante', 'Vecino', 'Abuelo', 'Bebe', 'Niño', 'Adolescente',
    'Adulto', 'Anciano', 'Ser Humano', 'Mujer', 'Hombre'
]
const personasFamosas = [
    "Albert Einstein", "Isaac Newton", "Marie Curie", "Leonardo da Vinci",
    "Galileo Galilei", "Charles Darwin", "Nikola Tesla", "Thomas Edison",
    "Mahatma Gandhi", "Nelson Mandela", "Martin Luther King Jr.", "Abraham Lincoln", "George Washington",
    "Cleopatra", "Juana de Arco", "Frida Kahlo", "Vincent van Gogh",
    "Pablo Picasso", "Salvador Dalí", "Ludwig van Beethoven", "Wolfgang Amadeus Mozart",
    "William Shakespeare",
    "Augusto Roa bastos", "Jose Luis Chilavert", "Berta Rojas", "Luis Alberto del Parana",
    "Silvio Pettirossi",
]
// List of Person, being or place
export const personList: string[] = [
    ...countries,
    ...profesiones,
    ...animales,
    ...lugaresGenericos,
    ...personasGenericas,
    ...personasFamosas,
];

// List of Objects
export const objectList: string[] = [
    'Mesa', 'Silla', 'Computadora', 'Teléfono', 'Libro', 'Lápiz',
    'Bolígrafo', 'Reloj', 'Llave', 'Zapato', 'Sombrero', 'Cuchara',
    'Cuchillo', 'Tenedor', 'Plato', 'Vaso', 'Botella', 'Cámara',
    'Espejo', 'Televisor', 'Radio', 'Parlante', 'Auriculares', 'Bicicleta',
    'Coche', 'Moto', 'Camión', 'Barco', 'Avión', 'Tren',
    'Pelota', 'Juguete', 'Ropa', 'Bolso', 'Carpeta', 'Cuaderno',
    'Gafas', 'Sombrilla', 'Linterna', 'Herramienta', 'Destornillador',
    'Martillo', 'Sierra', 'Taladro', 'Escalera', 'Caja', 'Maleta',
    'Cuchara de madera', 'Batidora', 'Tostadora', 'Microondas', 'Horno',
    'Lavadora', 'Secadora', 'Aspiradora', 'Plancha', 'Ventilador',
    'Calentador', 'Refrigerador', 'Congelador', 'Cafetera', 'Exprimidor',
    'Licuadora', 'Robot de cocina', 'Freidora', 'Parrilla', 'Barbacoa',
    'Bañera', 'Ducha', 'Inodoro', 'Lavabo', 'Espejo de baño', 'Toalla',
    'Jabón', 'Champú', 'Acondicionador', 'Cepillo de dientes', 'Pasta de dientes',
    'Maquinilla de afeitar', 'Secador de pelo', 'Rizador de pelo', 'Plancha para el pelo',
    'Cortauñas', 'Pinzas', 'Espejo de mano', 'Perfume', 'Desodorante',
    'Maquillaje', 'Protector solar', 'Labial', 'Destornillador', 'Joyas',
    'Anillo', 'Collar', 'Pulsera', 'Pendientes', 'Reloj inteligente', 'Gafas de sol',
    'Bastón', 'Silla de ruedas', 'Andador', 'Muletas', 'Audífonos', 'Celular', 'carro', 'viveres',
    'Tomate', 'Cebolla', 'Ajo', 'Pimiento', 'Zanahoria', 'Lechuga',
    'Pepino', 'Brócoli', 'Coliflor', 'Espinaca', 'Berenjena', 'Calabacín',
    'Papa', 'Batata', 'Maíz'
]

// List of Actions
export const actionList: string[] = [
    'Correr', 'Saltar', 'Nadar', 'Bailar', 'Cantar', 'Hablar',
    'Escribir', 'Leer', 'Dibujar', 'Pintar', 'Cocinar', 'Limpiar',
    'Jugar', 'Estudiar', 'Trabajar', 'Conducir', 'Volar', 'Pescar',
    'Cazar', 'Escalar', 'Caminar', 'Reír', 'Llorar', 'Dormir',
    'Despertar', 'Vestirse', 'Desvestirse', 'Peinarse', 'Maquillarse',
    'Afeitarse', 'Bañarse', 'Cepillarse los dientes', 'Hacer ejercicio',
    'Practicar deporte', 'Hacer yoga', 'Meditar', 'Relajarse', 'Escuchar música',
    'Ver televisión', 'Ir de compras', 'Hacer turismo', 'Viajar', 'Explorar',
    'Tomar fotos', 'Grabar video', 'Hablar por teléfono', 'Enviar mensaje',
    'Jugar videojuegos', 'Ejercitarse',
    'Regar las plantas', 'Limpiar la casa',
    'Comprar viveres', 'Preparar la comida', 'Hacer la cama', 'Lavar los platos',
    'Reparar', 'Construir', 'Arreglar', 'Pintar la pared', 'Organizar',
    'Planificar', 'Investigar', 'Aprender', 'Enseñar',
]

//List of difficult words to draw
export const difficultList: string[] = [
    'Cerebro', 'Átomo', 'Galaxia', 'Eclipse', 'Paradoja', 'Cuántico',
    'Metáfora', 'Simetría', 'Ecuación', 'Paralelogramo', 'Hipotenusa',
    'Espectro', 'Cromosoma', 'Ecosistema', 'Neurona', 'Fotón',
    'Antimateria', 'Holograma', 'Cibernético', 'Infinito', 'Entropía', 'Fractal', 'Paradoja',
    'Metamorfosis', 'Caleidoscopio', 'Espectroscopia',
    'Quasar', 'Acelerador de partículas', 'Nanotecnología', 'Biotecnología',
    'Genética', 'Astrobiología', 'Neurociencia', 'Física cuántica',
    'Impuestos', 'Economía', 'Democracia', 'Capitalismo',
    'Socialismo', 'Globalización', 'Sostenibilidad', 'Antropología',
    'Psicología', 'Filosofía', 'Epistemología', 'Ontología', 'Metafísica',
    'Clima', 'Biodiversidad', 'Energía renovable', 'Cambio climático',
    'Internet', 'Inteligencia artificial', 'Blockchain', 'Ciberseguridad',
    'Realidad virtual', 'Realidad aumentada',
    'Impresión 3D', 'Robótica', 'Drones', 'Telemedicina', 'Teletrabajo',
    'Consentimiento', 'Privacidad', 'Ciberacoso', 'Desinformación',
    'Censura', 'Libertad de expresion', 'Derechos humanos', 'Ética',
    'Love bombing', 'Gaslighting', 'Codependencia', 'Empatía',
    'Meditacion', 'Relajado', 'Nervioso', 'Ansioso', 'Estrés', 'Felicidad',
    'Tristeza', 'Enojo', 'Miedo', 'Sorpresa', 'Confusión', 'Aburrimiento',
    'Frustración', 'Alivio', 'Esperanza', 'Desesperación',
]

// List of "all play" words
export const allplayList: string[] = []

// Default word lists by category
export const wordListByType: Record<ItemType, string[]> = {
    person: personList,
    object: objectList,
    action: actionList,
    difficult: difficultList,
    allplay: [...allplayList, ...personList, ...objectList, ...actionList, ...difficultList],
}
